apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pl-serverless
  namespace: piglatin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/piglatin/demo-piglatin:latest
          env:
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-signing-secret
                  key: SLACK_SIGNING_SECRET


